apiVersion: v1
kind: Service
metadata:
  name: kafkaservice1
  labels:
    app: kafka
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookpr
