apiVersion: v1
kind: Pod
metadata:
  name: zookpr-pod
  labels:
    app: zookpr
spec:
  containers:
    - name:  kafka
      image: digitalwonderland/zookeeper
      ports:
        - containerPort: 2181
      env:
      - name: ZOOKEEPER_ID
        value: "1"
      - name: ZOOKEEPER_SERVER_1
        value: zoo1
